'use client'
import './globals.css'
import { Inter } from 'next/font/google'

import {
  QueryClient,
  QueryClientProvider,
} from '@tanstack/react-query'
import Script from 'next/script'

const queryClient = new QueryClient()
// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">

      <QueryClientProvider client={queryClient}>
        <body >
        <Script
            src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
            integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
            crossOrigin="anonymous"
          ></Script>

       
          <Script
            src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js"
            integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm"
            crossOrigin="anonymous"
          ></Script>
 
          {children}
 
        </body>
      </QueryClientProvider>


    </html>
  )
}
